### PR TITLE
Darkened icons and added a few for resources as testing

### PR DESCRIPTION
**Pull request by KaiserSoze**
I have the template for those icons, so create more should be quite easy.
(We should make reference to Alternate Resources, many of the icons are modification from theirs)

### CODE REVIEW

**Comment by Kerbas-ad-astra** [comment]
A statement like "some [all? give a list? or just list any which aren't?] resource icons based on Olympic1's resource icon pack, licensed under CC-BY-NC-SA 4.0" (with a link to the thread and such) in the readme, in the download's license file, and in the FilterExtension thread would do the trick.

**Comment by KaiserSoze** [comment]
Resource icons will have very little exceptions because I plan on following the same style even for some of the new ones that could arise. So we could left it as "Resource icons based on...".

**Comment by Olympic1** [comment]
The BioMass logo can change, I'm talking with seanth to include my BioMass logo's in his mod. I'll let you know if it changes.

**Comment by KaiserSoze** [comment]
I have also changed the mod icons to be black instead of white when they are not selected. More similar to the way the other icons are behaving.

**Pull request merged**
